name: Pipeline 1

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "hello world !!"

  job2:
    runs-on: windows-latest
    needs: [ job1 ]
    steps:
      - name: My awesome step
        run: mkdir app
      - name: My other awesome step
        run: dir